In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from scipy.stats.mstats import winsorize
from sklearn.preprocessing import PolynomialFeatures
import statsmodels.api as sm
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from statsmodels.tools.eval_measures import mse, rmse
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from scipy.stats import jarque_bera
from scipy.stats import normaltest
import warnings
pd.options.display.max_columns = None
warnings.filterwarnings('ignore')
sns.set_style("whitegrid")
baslik_font = {'family': 'arial', 'color': 'darkred','weight': 'bold','size': 13 }
eksen_font  = {'family': 'arial', 'color': 'darkblue','weight': 'bold','size': 10 }

## with Regression Project

In [163]:
df_energy_app = pd.read_csv("clean_energy_appliances")

In [175]:
features = ['lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3',
         'RH_6',  'RH_7',  'RH_8','hour1', 'house_T',   
             'tout_tdewpoint', 'hour*2', 
         'hour_avg', 'low_consum', 
          'high_consum']

y= df_energy_app["Appliances"]
X = df_energy_app[features]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=40)

### KNN

In [170]:
y[y>y.mean()] = 1

In [171]:
y[y<y.mean()] =0

In [172]:
y

0       1.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
3285    0.0
3286    1.0
3287    0.0
3288    0.0
3289    1.0
Name: Appliances, Length: 3290, dtype: float64

In [176]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
knn_model = KNeighborsClassifier(n_neighbors=5)


knn_model.fit(X_train,y_train)
knn_model.score(X_test,y_test)


0.8434650455927052

In [191]:
y_predict = knn_model.predict(X_test)
mse_predict = MSE(y_predict,y_test)
rmse_score = mse_predict**(1/2)
rmse_score

0.3956449853180182

### DecisionTreeRegression

In [184]:
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(max_depth=4)
y = df_hour_win_log["Appliances"]
X = df_hour_win_log[model1]

dec_tree_reg.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=4)

In [185]:
from sklearn.metrics import mean_squared_error as MSE
y_predict = dec_tree_reg.predict(X_test)
mse_predict = MSE(y_predict,y_test)
rmse_score = mse_predict**(1/2)

In [186]:
rmse_score

0.30225000072695846

In [187]:
dec_tree_reg.score(X_test,y_test)

0.6240737770822453

## with Classification project

In [84]:
from sklearn.metrics import classification_report, precision_recall_fscore_support
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
import os
from nltk.corpus import stopwords
from nltk.corpus import words
from nltk.stem import PorterStemmer

In [92]:
df_bbc = pd.read_csv("clean_bbc")

In [94]:
vectorizer = CountVectorizer()
vectorizer.fit(df_bbc["text"])

CountVectorizer()

In [97]:
text_vector = vectorizer.fit_transform(df_bbc.text)
text_vector_array = text_vector.toarray()
features = vectorizer.get_feature_names()

In [100]:
from sklearn.feature_extraction.text import TfidfVectorizer
Tfidf_Vector = TfidfVectorizer(min_df = 0., max_df = 1., use_idf = True)
Tfidf_Matrix = Tfidf_Vector.fit_transform(df_bbc.text)
Tfidf_Matrix = Tfidf_Matrix.toarray()
print(Tfidf_Matrix)

features = Tfidf_Vector.get_feature_names()

Tfidf_df = pd.DataFrame(Tfidf_Matrix, columns = features)
Tfidf_df.head()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


aaa  aac  aadc  aaliyah  aaron  abacu  abandon  abat  abba  abbasi  abbey  \
0  0.0  0.0   0.0      0.0    0.0    0.0      0.0   0.0   0.0     0.0    0.0   
1  0.0  0.0   0.0      0.0    0.0    0.0      0.0   0.0   0.0     0.0    0.0   
2  0.0  0.0   0.0      0.0    0.0    0.0      0.0   0.0   0.0     0.0    0.0   
3  0.0  0.0   0.0      0.0    0.0    0.0      0.0   0.0   0.0     0.0    0.0   
4  0.0  0.0   0.0      0.0    0.0    0.0      0.0   0.0   0.0     0.0    0.0   

   abbott  abc  abdellatif  abdic  abdomin  abduct  abdullah  aberdeen  abeyi  \
0     0.0  0.0         0.0    0.0      0.0     0.0       0.0       0.0    0.0   
1     0.0  0.0         0.0    0.0      0.0     0.0       0.0       0.0    0.0   
2     0.0  0.0         0.0    0.0      0.0     0.0       0.0       0.0    0.0   
3     0.0  0.0         0.0    0.0      0.0     0.0       0.0       0.0    0.0   
4     0.0  0.0         0.0    0.0      0.0     0.0       0.0       0.0    0.0   

   abhorr  abid  abil  abl  ablebodi  abn  abnorm  abolish  abort  \
0     0.0   0.0   0.0  0.0       0.0  0.0     0.0      0.0    0.0   
1     0.0   0.0   0.0  0.0       0.0  0.0     0.0      0.0    0.0   
2     0.0   0.0   0.0  0.0       0.0  0.0     0.0      0.0    0.0   
3     0.0   0.0   0.0  0.0       0.0  0.0     0.0      0.0    0.0   
4     0.0   0.0   0.0  0.0       0.0  0.0     0.0      0.0    0.0   

   abortionist  abraham  abramovich  abroad  absa  absenc  absend  absende  \
0          0.0      0.0         0.0     0.0   0.0     0.0     0.0      0.0   
1          0.0      0.0         0.0     0.0   0.0     0.0     0.0      0.0   
2          0.0      0.0         0.0     0.0   0.0     0.0     0.0      0.0   
3          0.0      0.0         0.0     0.0   0.0     0.0     0.0      0.0   
4          0.0      0.0         0.0     0.0   0.0     0.0     0.0      0.0   

   absolut  absorb  absurd  abund  aburiz  abus  abysm  academ  academi  \
0      0.0     0.0     0.0    0.0     0.0   0.0    0.0     0.0      0.0   
1      0.0     0.0     0.0    0.0     0.0   0.0    0.0     0.0      0.0   
2      0.0     0.0     0.0    0.0     0.0   0.0    0.0     0.0      0.0   
3      0.0     0.0     0.0    0.0     0.0   0.0    0.0     0.0      0.0   
4      0.0     0.0     0.0    0.0     0.0   0.0    0.0     0.0      0.0   

   acapulco  acc  acceler  accept  access  accessori  accid  accident  \
0       0.0  0.0      0.0     0.0     0.0        0.0    0.0       0.0   
1       0.0  0.0      0.0     0.0     0.0        0.0    0.0       0.0   
2       0.0  0.0      0.0     0.0     0.0        0.0    0.0       0.0   
3       0.0  0.0      0.0     0.0     0.0        0.0    0.0       0.0   
4       0.0  0.0      0.0     0.0     0.0        0.0    0.0       0.0   

   acclaim  accolad  accommod  accomod  accompani  accomplic  accomplish  \
0      0.0      0.0       0.0      0.0        0.0        0.0         0.0   
1      0.0      0.0       0.0      0.0        0.0        0.0         0.0   
2      0.0      0.0       0.0      0.0        0.0        0.0         0.0   
3      0.0      0.0       0.0      0.0        0.0        0.0         0.0   
4      0.0      0.0       0.0      0.0        0.0        0.0         0.0   

   accord  accordingli   account  accra  accumul  accur  accuraci  accus  \
0     0.0          0.0  0.063643    0.0      0.0    0.0       0.0    0.0   
1     0.0          0.0  0.129769    0.0      0.0    0.0       0.0    0.0   
2     0.0          0.0  0.000000    0.0      0.0    0.0       0.0    0.0   
3     0.0          0.0  0.000000    0.0      0.0    0.0       0.0    0.0   
4     0.0          0.0  0.000000    0.0      0.0    0.0       0.0    0.0   

   accustom  ace  aceh  achiev  achil  acknowleadg  acoust  acpo  acquir  \
0       0.0  0.0   0.0     0.0    0.0          0.0     0.0   0.0     0.0   
1       0.0  0.0   0.0     0.0    0.0          0.0     0.0   0.0     0.0   
2       0.0  0.0   0.0     0.0    0.0          0.0     0.0   0.0     0.0   
3       0.0  0.0   0.0     0.0    0.0      

In [102]:
X = Tfidf_Matrix
y = df_bbc.category.values

In [161]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=111)

### KNN

In [133]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
knn_model = KNeighborsClassifier(n_neighbors=5)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=40)

#y_predict = knn_model.predict(X_test)
knn_model.fit(X_train,y_train)
knn_model.score(X_test,y_test)

0.9348314606741573

### DecisionTreeClassifier

In [135]:
import scipy
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import pydotplus
import graphviz

In [154]:
dec_tree_model = DecisionTreeClassifier(
    criterion='entropy',
    max_features=10,
    max_depth=32,
    random_state = 1337)

dec_tree_model.fit(X_train,y_train)
y_predict = dec_tree_model.predict(X_test)
dec_tree_model.score(X_test,y_test)

0.5280898876404494

### LogisticRegression

In [160]:
log_reg_model = LogisticRegression(multi_class="multinomial",solver="lbfgs")
log_reg_model.fit(X_train,y_train)
log_reg_model.score(X_test,y_test)

0.9730337078651685